name: CI_$(date:yyyyMMdd)$(rev:.r)

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - TeePee.Refit/*
    - CI.TeePee.Refit.yml

pr: 
  branches:
    include:
    - main
  paths:
    include:
    - TeePee.Refit/*
    - CI.TeePee.Refit.yml
 
pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/TeePee.Refit.sln'
  buildConfiguration: 'Release'
  NUGET_PACKAGES: $(Pipeline.Workspace)/.nuget/packages

steps:
- task: UseDotNet@2
  displayName: 'Use .NET 7'
  inputs:
    version: 7.x

- task: Cache@2
  displayName: 'NuGet Pipeline Cache'
  inputs:
    key: 'nuget | "$(Agent.OS)" | TeePee.Refit/**/packages.lock.json,!**/bin/**,!**/obj/**'
    restoreKeys: |
       nuget | "$(Agent.OS)"
       nuget
    path: '$(NUGET_PACKAGES)'

- task: DotNetCoreCLI@2
  displayName: 'Restore Solution'
  inputs:
    command: 'restore'
    projects: '$(solution)'
    arguments: '-c $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Build Solution'
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: '-c $(buildConfiguration) --no-restore'

- task: DotNetCoreCLI@2
  displayName: 'Unit Tests'
  inputs:
    command: 'test'
    projects: 'TeePee.Refit/*[Tt]ests/*.csproj'
    arguments: '-c $(buildConfiguration) --no-build'
