name: CI_$(date:yyyyMMdd)$(rev:.r)

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - TeePee.Refit/*
    - CI.TeePee.Refit.yml

pr: 
  branches:
    include:
    - main
  paths:
    include:
    - TeePee.Refit/*
    - CI.TeePee.Refit.yml
 
pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/TeePee.Refit.sln'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Build All'
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: '-c $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Unit Tests'
  inputs:
    command: 'test'
    projects: 'TeePee.Refit/*[Tt]ests/*.csproj'
    arguments: '-c $(buildConfiguration) --no-build'
