name: $(date:yyyyMMdd)$(rev:.r)

trigger: none

pr:
  branches:
    include:
      - main
  paths:
    include:
      - TeePee/*
      - CI.TeePee.yml

pool:
  vmImage: "windows-latest"

variables:
  solution: "**/TeePee.sln"
  buildConfiguration: "Release"
  NUGET_PACKAGES: $(Pipeline.Workspace)/.nuget/packages

steps:
  - task: UseDotNet@2
    displayName: "Use .NET 9"
    inputs:
      version: 9.x

  - task: Cache@2
    displayName: "NuGet Pipeline Cache"
    inputs:
      key: 'nuget | "$(Agent.OS)" | TeePee/**/packages.lock.json,!**/bin/**,!**/obj/**'
      restoreKeys: |
        nuget | "$(Agent.OS)"
        nuget
      path: "$(NUGET_PACKAGES)"

  - task: DotNetCoreCLI@2
    displayName: "Restore Solution"
    inputs:
      command: "restore"
      projects: "$(solution)"
      arguments: "-c $(buildConfiguration)"

  - task: DotNetCoreCLI@2
    displayName: "Build Solution"
    inputs:
      command: "build"
      projects: "$(solution)"
      arguments: "-c $(buildConfiguration) --no-restore"

  - task: DotNetCoreCLI@2
    displayName: "Unit Tests"
    inputs:
      command: "test"
      projects: "TeePee/**/*[Tt]ests.csproj"
      arguments: "-c $(buildConfiguration) --no-build -- -results-directory $(Agent.TempDirectory) -report-trx"
